#!/usr/bin/env python
"""Smoke-test: full EngageNet forward pass on CPU with synthetic data.

Generated by Claude Sonnet 4.6

Usage (from repo root):
    python tests/test_model.py
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
import sys

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from config import CORE_MODALITIES, EngageNetConfig
from model import EngageNet
from read_data import ROLES, log


def main() -> None:
    cnfg = EngageNetConfig(active_modalities=CORE_MODALITIES)
    M = len(cnfg.modality_names) * 2  # features x roles
    B, L = 2, cnfg.window_len

    log.info(f"Active modalities: {cnfg.modality_names}")
    log.info(f"M={M}, B={B}, L={L}, C'={cnfg.shared_dim}")

    rng = jax.random.PRNGKey(cnfg.seed)
    rng_init, rng_gumbel, rng_data = jax.random.split(rng, 3)

    # Synthetic inputs: dict{role.feat: (B, C_i, L)}
    inputs = {}
    for i, feat in enumerate(cnfg.modality_names):
        c_in = cnfg.input_dim(feat)
        for role in ROLES:
            key = f"{role}.{feat}"
            inputs[key] = jax.random.normal(jax.random.fold_in(rng_data, i), (B, c_in, L))

    model = EngageNet(cnfg=cnfg)
    variables = model.init(rng_init, inputs, tau=1.0, rng=rng_gumbel, train=False)

    param_count = sum(x.size for x in jax.tree.leaves(variables["params"]))
    log.info(f"Total params: {param_count:,}")

    # Forward pass
    (multi_alpha, multi_beta, unimodal), updates = model.apply(
        variables, inputs, tau=1.0, rng=rng_gumbel, train=False, mutable=["batch_stats"]
    )

    log.info(f"multi_alpha: {multi_alpha.shape}  multi_beta: {multi_beta.shape}")
    assert multi_alpha.shape == (B, cnfg.window_len)
    assert multi_beta.shape == (B, cnfg.window_len)

    for k, (a, b) in sorted(unimodal.items()):
        log.info(f"  {k:45s}  alpha={a.shape} beta={b.shape}")
        assert a.shape == (B, cnfg.window_len)
        assert b.shape == (B, cnfg.window_len)

    # Sanity: alpha, beta > 1 (unimodal Beta)
    assert (multi_alpha > 1).all(), f"multi_alpha has values <= 1: {multi_alpha}"
    assert (multi_beta > 1).all(), f"multi_beta has values <= 1: {multi_beta}"

    log.info("Full model smoke-test passed!")


if __name__ == "__main__":
    main()

