#!/usr/bin/env python
"""Smoke-test: verify InterModalBiMamba on CPU.

Generated by Claude Sonnet 4.6

Checks:
1. P is doubly stochastic (rows and columns sum to 1)
2. Output shape is correct (B, L', MC')
3. Equivariance: permuting input modalities does not change the output

Usage (from repo root):
    python tests/test_inter_modal.py
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
import sys

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from inter_modal import InterModalBiMamba
from read_data import log


def main() -> None:
    B, Lp, Cp, M = 2, 250, 128, 8  # 4 modalities x 2 roles
    D = M * Cp  # MC' = 1024

    rng = jax.random.PRNGKey(95)
    rng_init, rng_gumbel, rng_data = jax.random.split(rng, 3)

    # Fake hiddens dict
    keys = [f"expert.mod{i}" for i in range(M // 2)] + [f"novice.mod{i}" for i in range(M // 2)]
    keys = sorted(keys)
    hiddens = {k: jax.random.normal(jax.random.fold_in(rng_data, i), (B, Lp, Cp)) for i, k in enumerate(keys)}

    model = InterModalBiMamba(D=D, N=16, D_C=4, GS_dim=64, n_iters=20)

    variables = model.init(rng_init, hiddens, tau=1.0, rng=rng_gumbel, train=False)
    param_count = sum(x.size for x in jax.tree.leaves(variables["params"]))
    log.info(f"InterModalBiMamba params: {param_count:,}")

    # Forward pass
    H, updates = model.apply(variables, hiddens, tau=1.0, rng=rng_gumbel, train=False, mutable=["batch_stats"])
    log.info(f"Output shape: {H.shape}  (expected ({B}, {Lp}, {D}))")
    assert H.shape == (B, Lp, D), f"Shape mismatch: {H.shape}"

    # Check P is doubly stochastic
    gs_vars = {"params": {k: v for k, v in variables["params"].items() if "gumbel_sinkhorn" in k}}
    # Extract P by running just the GumbelSinkhorn submodule
    from inter_modal import GumbelSinkhorn, sinkhorn
    stacked = jnp.stack([hiddens[k] for k in keys], axis=1)
    summaries = stacked.mean(axis=2)  # (B, M, C')
    gs = GumbelSinkhorn(M=M, d_key=64, n_iters=10)
    gs_variables = gs.init(rng_init, summaries, tau=1.0, rng=rng_gumbel)
    P = gs.apply(gs_variables, summaries, tau=1.0, rng=rng_gumbel)
    row_sums = P.sum(axis=-1)
    col_sums = P.sum(axis=-2)
    log.info(f"P row sums max error: {jnp.abs(row_sums - 1.0).max():.6f}")
    log.info(f"P col sums max error: {jnp.abs(col_sums - 1.0).max():.6f}")
    assert jnp.abs(row_sums - 1.0).max() < 1e-3, "P rows don't sum to 1"
    assert jnp.abs(col_sums - 1.0).max() < 1e-3, "P cols don't sum to 1"

    log.info("All checks passed!")


if __name__ == "__main__":
    main()

