# Generated by Claude Sonnet 4.6

from __future__ import annotations

import argparse
import json
import numpy as np
import sys

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from metrics import ccc, combined_ccc, cdd_gender, cdd_language
from read_data import ROLES, log


def load_csv(path: Path) -> np.ndarray:
    return np.loadtxt(path, delimiter=";", dtype=np.float32)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--submission-dir", type=str, required=True)
    parser.add_argument("--data-root", type=str, required=True)
    parser.add_argument("--corpora", nargs="+", default=["NoXi", "NoXi+J"])
    parser.add_argument("--split", type=str, default="val")
    args = parser.parse_args()

    submission_dir = Path(args.submission_dir)
    data_root = Path(args.data_root)

    per_domain_cccs: dict[str, float] = {}

    for corpus in args.corpora:
        gt_dir = data_root / corpus / args.split
        pred_dir = submission_dir / corpus / args.split

        if not gt_dir.exists():
            log.info(f"Skipping {corpus}/{args.split} (ground-truth not found)")
            continue
        if not pred_dir.exists():
            log.info(f"Skipping {corpus}/{args.split} (predictions not found)")
            continue

        all_preds = []
        all_targets = []

        session_dirs = sorted([p for p in gt_dir.iterdir() if p.is_dir()])

        for session_dir in session_dirs:
            pred_session = pred_dir / session_dir.name

            for role in ROLES:
                gt_path = session_dir / f"{role}.engagement.annotation.csv"
                pred_path = pred_session / f"{role}.engagement.annotation.csv"

                if not gt_path.exists() or not pred_path.exists():
                    continue

                gt = load_csv(gt_path)
                pred = load_csv(pred_path)

                min_len = min(len(gt), len(pred))
                all_preds.append(pred[:min_len])
                all_targets.append(gt[:min_len])

        if not all_preds:
            log.info(f"{corpus}/{args.split}: no valid sessions")
            continue

        corpus_preds = np.concatenate(all_preds)
        corpus_targets = np.concatenate(all_targets)
        corpus_ccc = ccc(corpus_preds, corpus_targets)
        per_domain_cccs[corpus] = corpus_ccc
        log.info(f"{corpus}/{args.split}: CCC = {corpus_ccc:.4f} ({len(session_dirs)} sessions, {len(corpus_preds)} frames)")

    if per_domain_cccs:
        c_ccc = combined_ccc(per_domain_cccs)
        log.info(f"Combined CCC: {c_ccc:.4f}")

    results = {"per_domain_ccc": per_domain_cccs, "combined_ccc": c_ccc if per_domain_cccs else None}
    out_path = submission_dir / "results.json"
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    log.info(f"Results saved to {out_path}")


if __name__ == "__main__":
    main()